config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'brisa(/:act)', to: 'brisa#api_request', namespace: 'Brisa0'

  if Rails.env == 'development'
    resources :library_generator
  end
end

app/controllers/library_generator_controller.rb
BrisaEntry; BrisaUser; BrisaModel; BrisaUserSetting; BrisaGroup; BrisaRole; BrisaComment; BrisaNotification

class LibraryGeneratorController < ApplicationController
  LANGUAGES = %w(javascript ruby python)

  def index
    @dispatcher = BrisaApiDispatcher.singleton
  end

  def show
    @namespace, @lang = params[:id].split(':')
    @dispatcher = BrisaApiDispatcher.singleton
    @ns = @dispatcher.ns[@namespace]
    if @ns.nil?
      render html: "#{ns} not found" and return
    elsif !LANGUAGES.include?(@lang)
      render html: "#{@lang} not supported" and return
    end
    @objs = @ns.objects.keys
    render 'show.txt.erb', content_type: 'text/plain', layout: false
  end
end

app/helpers/library_generator_helper.rb
module LibraryGeneratorHelper
  def ObjActions(obj)
    @ns.objects[obj].actions.keys
  end

  def ActionOpts(obj, action)
    @ns.objects[obj].actions[action][:opts]
  end

  def InstanceMethods(obj)
    inst_methods = {}
    @ns.objects[obj].actions.each do |k,v|
      inst_methods[k] = v[:opts] if v[:opts][:instance]
    end
    inst_methods
  end

  def InstanceArgs(opts)
    rem_args = Array(opts[:instance]) + Array(opts[:include_data])
    arg_list = opts[:args] - rem_args.map(&:to_s)
    #puts "InstArgs: (#{arg_list.join(",")})" + opts.inspect + " -- #{rem_args}"
    return arg_list
  end

  def ActionReturnType(opts, lang_null='null', cls_prefix='Brisa', cls=nil)
    if opts[:returns].is_a? Array
      return cls_prefix + opts[:returns][0]
    elsif opts[:returns] == :data or opts[:returns].nil?
      return lang_null
    elsif opts[:returns] == :self
      return cls ? cls_prefix + cls : lang_null
    else
      return cls_prefix + opts[:returns]
    end
  end
end

app/views/library_generator/index.html.erb
<h2>Brisa Library Generator</h2>

<h3>Namespaces</h3>

<% @dispatcher.ns.keys.each do |ns| %>
<div style="margin-left: 10px;">
<h3><%= ns %></h3>
  <div>
    <%= link_to 'Ruby', library_generator_path("#{ns}:ruby") %> |
    <%= link_to 'JavaScript', library_generator_path("#{ns}:javascript") %> |
    <%= link_to 'Python', library_generator_path("#{ns}:python") %>
  </div>

  <% @dispatcher.ns[ns].objects.keys.each do |obj| %>
    <div style="margin-left: 10px;">
    <h4><%= obj %> ( <%= @dispatcher.ns[ns].objects[obj].opts[:attrs].join(", ") %> )</h4>

    <% @dispatcher.ns[ns].objects[obj].actions.keys.each do |act|
      action = @dispatcher.ns[ns].objects[obj].actions[act]
      %>
      <div style="margin-left: 10px; margin-top: 10px">
        <% if action[:opts][:desc] %><small># <%= action[:opts][:desc] %></small><br/><% end %>
        <%= act %>(
        <%= @dispatcher.ns[ns].objects[obj].actions[act][:opts][:args].join(", ") %> )
        <%# @dispatcher.ns[ns].objects[obj].actions[act][:opts] %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>
<% end %>

app/views/library_generator/show.txt.erb
<%= render "library_generator/#{@lang}/boiler_top" %>